// Protocol.swift — handwritten WebSocket transport types for Spaceskit.
// Canonical cross-process contracts live in /proto; this file keeps the
// remaining first-party Swift transport aligned without shim-generated code.

import Foundation

// MARK: - Message Envelope

/// JSON envelope for all gateway protocol messages.
public struct GatewayMessage<T: Codable>: Codable {
    public let type: String
    public let id: String
    public var replyTo: String?
    public let ts: String
    public let payload: T

    public init(type: String, id: String, replyTo: String? = nil, payload: T) {
        self.type = type
        self.id = id
        self.replyTo = replyTo
        self.ts = ISO8601DateFormatter().string(from: Date())
        self.payload = payload
    }
}

// MARK: - Client → Gateway Payloads

// MARK: - Known Message Types

public enum MessageType {
    // Client → Gateway
    public static let authenticate = "authenticate"
    public static let executeTurn = "execute_turn"
    public static let cancelTurn = "cancel_turn"
    public static let resumeFeedback = "resume_feedback"
    public static let subscribe = "subscribe"
    public static let capabilityInvoke = "capability_invoke"
    public static let spaceCreate = "space.create"
    public static let spaceGet = "space.get"
    public static let spaceList = "space.list"
    public static let spaceArchive = "space.archive"
    public static let spaceDelete = "space.delete"
    public static let spaceUpdateMetadata = "space.update_metadata"
    public static let spaceAddAgent = "space.add_agent"
    public static let spaceRemoveAgent = "space.remove_agent"
    public static let spaceUpdateAgentAssignment = "space.update_agent_assignment"
    public static let spaceSetOrchestrator = "space.set_orchestrator"
    public static let spaceSetThinkingCapturePolicy = "space.set_thinking_capture_policy"
    public static let spaceGetMemoryPolicy = "space.get_memory_policy"
    public static let spaceSetMemoryPolicy = "space.set_memory_policy"
    public static let spaceEndIncognitoSession = "space.end_incognito_session"
    public static let spaceListAgentAssignments = "space.list_agent_assignments"
    public static let spaceGetMcpEndpoint = "space.get_mcp_endpoint"
    public static let spaceSetMcpEndpoint = "space.set_mcp_endpoint"
    public static let spaceClearMcpEndpoint = "space.clear_mcp_endpoint"
    public static let spaceDiscoverMcpAgents = "space.discover_mcp_agents"
    public static let spaceApproveMcpAgent = "space.approve_mcp_agent"
    public static let spaceAddSkill = "space.add_skill"
    public static let spaceRemoveSkill = "space.remove_skill"
    public static let spaceListSkills = "space.list_skills"
    public static let spaceGetWorkspace = "space.get_workspace"
    public static let spaceSetWorkspace = "space.set_workspace"
    public static let spaceOpenWorkspace = "space.open_workspace"
    public static let spaceAddResource = "space.add_resource"
    public static let spaceRemoveResource = "space.remove_resource"
    public static let spaceListResources = "space.list_resources"
    public static let spaceListTurns = "space.list_turns"
    public static let spaceListOrchestrationJournal = "space.list_orchestration_journal"
    public static let identityListAgentDefinitions = "identity.list_agent_definitions"
    public static let identityGetAgentDefinition = "identity.get_agent_definition"
    public static let identityCreateAgentDefinition = "identity.create_agent_definition"
    public static let identityUpdateAgentDefinition = "identity.update_agent_definition"
    public static let identityArchiveAgentDefinition = "identity.archive_agent_definition"
    public static let identityListPersonas = "identity.list_personas"
    public static let identityGetPersona = "identity.get_persona"
    public static let identityCreatePersona = "identity.create_persona"
    public static let identityUpdatePersona = "identity.update_persona"
    public static let identityArchivePersona = "identity.archive_persona"
    public static let identityPreviewCompiledInstructions = "identity.preview_compiled_instructions"
    public static let identityPreviewRuntimeSystemPrompt = "identity.preview_runtime_system_prompt"
    public static let identityPreviewSystemPromptMatrix = "identity.preview_system_prompt_matrix"
    public static let spaceListTemplates = "space.list_templates"
    public static let spaceGetTemplate = "space.get_template"
    public static let spacePreviewTemplate = "space.preview_template"
    public static let spaceCreateFromTemplate = "space.create_from_template"
    public static let spaceSaveTemplate = "space.save_template"
    public static let spaceArchiveTemplate = "space.archive_template"
    public static let spaceTemplateList = "space_template.list"
    public static let spaceTemplateGet = "space_template.get"
    public static let spaceTemplatePreview = "space_template.preview"
    public static let spaceTemplateCreateSpace = "space_template.create_space"
    public static let spaceTemplateSave = "space_template.save"
    public static let spaceTemplateArchive = "space_template.archive"
    public static let libraryListEntries = "library.list_entries"
    public static let libraryGetEntry = "library.get_entry"
    public static let librarySaveSkill = "library.save_skill"
    public static let libraryImportEntry = "library.import_entry"
    public static let libraryArchiveEntry = "library.archive_entry"
    public static let librarySetEntryEnabled = "library.set_entry_enabled"
    public static let libraryDeleteEntry = "library.delete_entry"
    public static let libraryScanEntries = "library.scan_entries"
    public static let libraryListSkillDrafts = "library.list_skill_drafts"
    public static let libraryGetSkillDraft = "library.get_skill_draft"
    public static let libraryCreateSkillDraft = "library.create_skill_draft"
    public static let libraryDeleteSkillDraft = "library.delete_skill_draft"
    public static let gatewayDiscoverLocalAgents = "gateway.discover_local_agents"
    public static let gatewayListProviderConfigs = "gateway.list_provider_configs"
    public static let gatewayGetRuntimeDefaults = "gateway.get_runtime_defaults"
    public static let gatewaySetRuntimeDefaults = "gateway.set_runtime_defaults"
    public static let gatewayGetMainAgent = "gateway.get_main_agent"
    public static let gatewaySetMainAgent = "gateway.set_main_agent"
    public static let gatewayGetConciergeAgent = "gateway.get_concierge_agent"
    public static let gatewaySetConciergeAgent = "gateway.set_concierge_agent"
    public static let gatewayListAvailableModels = "gateway.list_available_models"
    public static let gatewayListProviderCatalogs = "gateway.list_provider_catalogs"
    public static let gatewayListInterconnectors = "gateway.list_interconnectors"
    public static let gatewayRescanInterconnectors = "gateway.rescan_interconnectors"
    public static let toolList = "tool.list"
    public static let toolGet = "tool.get"
    public static let toolScaffold = "tool.scaffold"
    public static let toolRegister = "tool.register"
    public static let toolRemove = "tool.remove"
    public static let toolSetEnabled = "tool.set_enabled"
    public static let toolListGrants = "tool.list_grants"
    public static let toolRevokeGrant = "tool.revoke_grant"
    public static let gatewayGetProviderTelemetry = "gateway.get_provider_telemetry"
    public static let gatewayGetLocalUsageTelemetry = "gateway.get_local_usage_telemetry"
    public static let gatewayGetWorkspaceDefaults = "gateway.get_workspace_defaults"
    public static let gatewaySetWorkspaceDefaults = "gateway.set_workspace_defaults"
    public static let gatewayGetMemoryDefaults = "gateway.get_memory_defaults"
    public static let gatewaySetMemoryDefaults = "gateway.set_memory_defaults"
    public static let gatewayGetExternalConnectivity = "gateway.get_external_connectivity"
    public static let gatewaySetExternalConnectivity = "gateway.set_external_connectivity"
    public static let gatewayGetProviderSettings = "gateway.get_provider_settings"
    public static let gatewayUpdateProviderSettings = "gateway.update_provider_settings"
    public static let gatewaySetProviderConfig = "gateway.set_provider_config"
    public static let gatewayRemoveProviderConfig = "gateway.remove_provider_config"
    public static let gatewayFactoryReset = "gateway.factory_reset"
    public static let gatewayProvisionLocalProfile = "gateway.provision_local_profile"
    public static let gatewayPutSecretRef = "gateway.put_secret_ref"
    public static let gatewayListSecretRefs = "gateway.list_secret_refs"
    public static let gatewayDeleteSecretRef = "gateway.delete_secret_ref"
    public static let gatewayGetIntegrationsSnapshot = "gateway.get_integrations_snapshot"
    public static let gatewayListConnectorFamilies = "gateway.list_connector_families"
    public static let gatewayListConnectors = "gateway.list_connectors"
    public static let gatewayUpsertConnector = "gateway.upsert_connector"
    public static let gatewayRemoveConnector = "gateway.remove_connector"
    public static let connectorSubmitInboundEvent = "connector.submit_inbound_event"
    public static let connectorInboundEventResult = "connector.inbound_event_result"
    public static let gatewayListConnectorBindings = "gateway.list_connector_bindings"
    public static let gatewayUpsertConnectorBinding = "gateway.upsert_connector_binding"
    public static let gatewayRemoveConnectorBinding = "gateway.remove_connector_binding"
    public static let gatewayGetConnectorPolicy = "gateway.get_connector_policy"
    public static let gatewayUpdateConnectorPolicy = "gateway.update_connector_policy"
    public static let gatewayGetToolPolicy = "gateway.get_tool_policy"
    public static let gatewayUpdateToolPolicy = "gateway.update_tool_policy"
    public static let gatewayListSafetyProfiles = "gateway.list_safety_profiles"
    public static let gatewayTestConnector = "gateway.test_connector"
    public static let gatewayGetPolicy = "gateway.get_policy"
    public static let gatewayUpdatePolicy = "gateway.update_policy"
    public static let gatewayKbListEntries = "gateway.kb_list_entries"
    public static let gatewayKbUpsertEntry = "gateway.kb_upsert_entry"
    public static let gatewayKbDeleteEntry = "gateway.kb_delete_entry"
    public static let gatewaySkillList = "gateway.skill_list"
    public static let gatewayListCapabilityGrants = "gateway.list_capability_grants"
    public static let gatewayGrantCapability = "gateway.grant_capability"
    public static let gatewayRevokeCapability = "gateway.revoke_capability"
    public static let usageGetSnapshot = "usage.get_snapshot"
    public static let schedulerCreateJob = "scheduler.create_job"
    public static let schedulerGetJob = "scheduler.get_job"
    public static let schedulerListJobs = "scheduler.list_jobs"
    public static let schedulerListEvalDefinitions = "scheduler.list_eval_definitions"
    public static let schedulerUpdateJob = "scheduler.update_job"
    public static let schedulerDeleteJob = "scheduler.delete_job"
    public static let schedulerLinkSpace = "scheduler.link_space"
    public static let schedulerUnlinkSpace = "scheduler.unlink_space"
    public static let schedulerListRuns = "scheduler.list_runs"
    public static let schedulerRunNow = "scheduler.run_now"
    public static let workbenchListQueue = "workbench.list_queue"
    public static let workbenchGetQueueItem = "workbench.get_queue_item"
    public static let workbenchCreateBatch = "workbench.create_batch"
    public static let workbenchListBatches = "workbench.list_batches"
    public static let workbenchUpdateBatch = "workbench.update_batch"
    public static let workbenchStartRun = "workbench.start_run"
    public static let workbenchRetryRun = "workbench.retry_run"
    public static let workbenchCancelRun = "workbench.cancel_run"
    public static let workbenchListRuns = "workbench.list_runs"
    public static let workbenchGetRun = "workbench.get_run"
    public static let workbenchApproveStage = "workbench.approve_stage"
    public static let workbenchRejectStage = "workbench.reject_stage"
    public static let workbenchSetMode = "workbench.set_mode"
    public static let workbenchListArtifacts = "workbench.list_artifacts"
    public static let workbenchGetPolicy = "workbench.get_policy"
    public static let workbenchUpdatePolicy = "workbench.update_policy"
    public static let orchestratorCommand = "orchestrator.command"
    public static let orchestratorGetCommand = "orchestrator.get_command"
    public static let spaceLink = "space.link"
    public static let spaceUnlink = "space.unlink"
    public static let spaceShareContext = "space.share_context"
    public static let spaceShareCreateInvite = "space.share_create_invite"
    public static let spaceShareJoin = "space.share_join"
    public static let spaceShareRevoke = "space.share_revoke"
    public static let spaceShareListParticipants = "space.share_list_participants"
    public static let spaceCreateChangeset = "space.create_changeset"
    public static let spaceListChangesets = "space.list_changesets"
    public static let spaceUploadChangesetFileInit = "space.upload_changeset_file_init"
    public static let spaceUploadChangesetFileComplete = "space.upload_changeset_file_complete"
    public static let spaceSubmitChangeset = "space.submit_changeset"
    public static let spaceReviewChangeset = "space.review_changeset"
    public static let spaceApplyChangeset = "space.apply_changeset"
    public static let spaceGetChangesetDiff = "space.get_changeset_diff"
    public static let spaceGetQuota = "space.get_quota"
    public static let spaceUpdateQuotaPolicy = "space.update_quota_policy"
    public static let spaceGetUsage = "space.get_usage"
    public static let spaceListActivityLog = "space.list_activity_log"
    public static let spaceGetTurnTrace = "space.get_turn_trace"
    public static let spaceListArtifacts = "space.list_artifacts"
    public static let spaceGetArtifact = "space.get_artifact"
    public static let spaceGetDebugArtifact = "space.get_debug_artifact"
    public static let spaceListExperiences = "space.list_experiences"
    public static let spaceGetExperience = "space.get_experience"
    public static let spaceListInsights = "space.list_insights"
    public static let spaceGetInsight = "space.get_insight"
    public static let spaceAcceptInsight = "space.accept_insight"
    public static let spaceRejectInsight = "space.reject_insight"
    public static let spaceDismissInsight = "space.dismiss_insight"
    public static let spaceGetSpaceAgentNotes = "space.get_space_agent_notes"
    public static let spaceUpdateSpaceAgentNotes = "space.update_space_agent_notes"
    public static let spaceGetUserProfile = "space.get_user_profile"
    public static let spaceUpdateUserProfile = "space.update_user_profile"
    public static let spaceListMemories = "space.list_memories"
    public static let spaceDeleteMemory = "space.delete_memory"
    public static let spaceUpdateMemoryImportance = "space.update_memory_importance"
    public static let spaceReset = "space.reset"
    public static let spaceResetAgentUsageSession = "space.reset_agent_usage_session"
    public static let spaceGetEffectiveTools = "space.get_effective_tools"
    public static let spaceGetEffectiveToolAccess = "space.get_effective_tool_access"
    public static let spaceGetToolPolicy = "space.get_tool_policy"
    public static let spaceUpdateToolPolicy = "space.update_tool_policy"
    public static let spaceGetConnectorPolicy = "space.get_connector_policy"
    public static let spaceUpdateConnectorPolicy = "space.update_connector_policy"
    public static let authRegisterDevice = "auth.register_device"
    public static let authRotateDeviceKey = "auth.rotate_device_key"
    public static let authRevokeDevice = "auth.revoke_device"
    public static let authListDevices = "auth.list_devices"
    public static let authIssueHttpPrincipalToken = "auth.issue_http_principal_token"
    public static let spacePullSharedContext = "space.pull_shared_context"
    public static let syncAnnounce = "sync.announce"
    public static let syncQueryResources = "sync.query_resources"
    public static let syncPullResources = "sync.pull_resources"
    public static let speechStart = "speech.start"
    public static let speechAudioChunk = "speech.audio_chunk"
    public static let speechControl = "speech.control"
    public static let conciergeCallStart = "concierge.call.start"
    public static let conciergeCallAnswer = "concierge.call.answer"
    public static let conciergeCallEnd = "concierge.call.end"
    public static let conciergeCallSetMuted = "concierge.call.set_muted"
    public static let conciergeCallAudioChunk = "concierge.call.audio_chunk"
    public static let conciergeCallControl = "concierge.call.control"
    public static let conciergeCallHandoffPrepare = "concierge.call.handoff.prepare"
    public static let conciergeCallHandoffAccept = "concierge.call.handoff.accept"
    public static let conciergeCallRegisterPush = "concierge.call.register_push"
    public static let ping = "ping"

    // Adapter ↔ Gateway
    public static let capabilitiesRegister = "capabilities.register"
    public static let capabilitiesDeregister = "capabilities.deregister"
    public static let capabilityInvokeAdapter = "capability.invoke"
    public static let capabilityResult = "capability.result"
    public static let capabilityError = "capability.error"

    // Gateway → Client
    public static let authChallenge = "auth_challenge"
    public static let authResult = "auth_result"
    public static let turnEvent = "turn_event"
    public static let turnStream = "turn_stream"
    public static let spaceState = "space_state"
    public static let spaceAgentUpdated = "space.agent_updated"
    public static let notification = "notification"
    public static let appNavigate = "app.navigate"
    public static let appConciergeActionRequest = "app.concierge_action_request"
    public static let orchestratorEvent = "orchestrator.event"
    public static let speechEvent = "speech.event"
    public static let conciergeCallEvent = "concierge.call.event"
    public static let error = "error"
    public static let pong = "pong"

    // Notifications
    public static let subscribeNotifications = "subscribe_notifications"
    public static let unsubscribeNotifications = "unsubscribe_notifications"
    public static let conciergeActionResult = "concierge.action_result"

    // Inter-Agent Messaging
    public static let agentMessage = "agent_message"
    public static let agentPoke = "agent_poke"
    public static let agentIdle = "agent_idle"

    // Task Dependencies
    public static let taskDependency = "task_dependency"
    public static let taskDependencyResolved = "task_dependency_resolved"
}

// MARK: - Raw Message (for initial parsing)

/// Partially-decoded message for type discrimination.
struct RawGatewayMessage: Codable {
    let type: String
    let id: String
    let replyTo: String?
    let ts: String
    let payload: AnyCodable?
}

/// Lightweight message envelope for routing — skips payload decode.
struct MessageEnvelope: Codable {
    let type: String
    let id: String
    let replyTo: String?
}
